### ISSUE TITLE
Add SLO tests to all SDK's

### ISSUE THREAD

**Issue by zeruk** [ydb-platform/slo-tests#20]
SDKs sorted by stars:
- [x] [Go](https://github.com/ydb-platform/ydb-go-sdk/issues/568)
- [ ] [Python](https://github.com/ydb-platform/ydb-python-sdk/issues/108)
- [x] [Node.js](https://github.com/ydb-platform/ydb-nodejs-sdk) PRs:[227](https://github.com/ydb-platform/ydb-nodejs-sdk/pull/227),[234](https://github.com/ydb-platform/ydb-nodejs-sdk/pull/234),[235](https://github.com/ydb-platform/ydb-nodejs-sdk/pull/235)
- [ ] [Rust](https://github.com/ydb-platform/ydb-rs-sdk/issues/122)
- [ ] [PHP](https://github.com/ydb-platform/ydb-php-sdk/issues/43)
- [ ] [Dotnet](https://github.com/ydb-platform/ydb-dotnet-sdk/issues/6)
- [ ] [Java](https://github.com/ydb-platform/ydb-java-sdk/issues/54)

**Comment by zeruk** [comment]
Go in progress 
https://github.com/ydb-platform/ydb-go-sdk/pull/671
https://github.com/ydb-platform/ydb-go-sdk/pull/669

**Comment by ilyakharev** [comment]
PHP in progress
[https://github.com/ydb-platform/ydb-php-sdk/pull/105](ydb-platform/ydb-php-sdk/#105)

**Comment by zeruk** [comment]
Congratulations 🎉!
