### ISSUE TITLE
feat: add Docker build arguments

### ISSUE THREAD

**Issue by zeruk** [ydb-platform/slo-tests#22]

**Comment by ImpressionableRaccoon** [comment]
Is this feature already implemented?
commit: https://github.com/ydb-platform/slo-tests/commit/ec69577a1003a0654efe6c1d3b986f6f30a9dc7e

**Comment by zeruk** [comment]
> Is this feature already implemented? commit: [ec69577](https://github.com/ydb-platform/slo-tests/commit/ec69577a1003a0654efe6c1d3b986f6f30a9dc7e)

Yes!
